# Base Image
FROM python:3.6.5-alpine


# install dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd


# Setting working directory
WORKDIR /app

# Dealing with requirements
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh


# Coping project
COPY . /app

# Running server
CMD ["/app/entrypoint.sh"]