"""empty message

Revision ID: 5c8cb2dc53b9
Revises: c4d7d15a174b
Create Date: 2018-11-18 23:54:49.043724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8cb2dc53b9'
down_revision = 'c4d7d15a174b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'teste')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('teste', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
