"""empty message

Revision ID: a2a1a1b527ef
Revises: 5c8cb2dc53b9
Create Date: 2018-11-23 17:26:19.550210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2a1a1b527ef'
down_revision = '5c8cb2dc53b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'total_cost')
    op.drop_column('report', 'total_tax_cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('total_tax_cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('report', sa.Column('total_cost', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
