"""empty message

Revision ID: cf24ff69a183
Revises: a2a1a1b527ef
Create Date: 2018-11-24 03:08:55.308012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf24ff69a183'
down_revision = 'a2a1a1b527ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'date_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('report', 'date_to',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'date_to',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('report', 'date_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
